version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bioguard
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bioguard-network

  app:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./userImages:/app/userImages
    env_file:
      - .env
    command: flask run --host=0.0.0.0 --port=5000
    networks:
      - bioguard-network

volumes:
  postgres_data:

networks:
  bioguard-network: